logging.level.org.springframework.cloud.kubernetes: DEBUG
spring.application.name: config-example

management:
  endpoints:
    web:
      exposure:
        include: info,refresh,keepalive,health
        
feign:
  url: http://localhost:8772/users